@api = http://localhost:4001/HC/product
### get all users

GET {{api}}

### create a user

POST {{api}}
Content-Type: application/json

{
 "name":"pepito",
 "password":"ajdaj13221",
 "email":"pepi@example.org",
 "role":"client"
}

###
DELETE {{api}}/65e721e58cf8c100d5f4005b
